apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-app
data:
  DJANGO_DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
